"use client"

// Placeholder for the toast hook - this would normally be generated by shadcn/ui
import { useState } from "react"

interface Toast {
  title: string
  description?: string
  variant?: "default" | "destructive"
}

export const useToast = () => {
  const [toasts, setToasts] = useState<Toast[]>([])

  const toast = (toast: Toast) => {
    setToasts((prev) => [...prev, toast])
    // In a real implementation, this would show the toast
    console.log("Toast:", toast)

    // Auto-remove toast after 3 seconds
    setTimeout(() => {
      setToasts((prev) => prev.slice(1))
    }, 3000)
  }

  return { toast, toasts }
}
